const QuestionActionTypes = {
	SET_QUESTIONS: 'SET_QUESTONS',
	APPEND_QUESTIONS: 'APPEND_QUESTIONS',
	UPDATE_QUESTION: 'UPDATE_QUESTION',
	REMOVE_QUESTION: 'REMOVE_QUESTION',
}

export default QuestionActionTypes
