const AnswerActionTypes = {
	SET_ANSWERS: 'SET_ANSWERS',
	UNSET_ANSWERS: 'UNSET_ANSWERS',
	ADD_ANSWER: 'ADD_ANSWER',
	UPDATE_ANSWER: 'UPDATE_ANSWER',
	APPEND_ANSWERS: 'APPEND_ANSWERS',
	ALL_LOADED: 'ALL_LOADED',
	REMOVE_ANSWER: 'REMOVE_ANSWER',
}

export default AnswerActionTypes
